spring:
  redis:
    database: 0
    host: 192.168.174.130
    port: 6379
    password: guest
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
          # 连接池中的最大空闲连接
          max-idle: 500
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 2000
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 0
  #连接池参数
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/febs-shiro
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20


